PWEB-P6/Controllers/UserRolesManagerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PWEB_P6.Models;
using PWEB_P6.ViewModels;

namespace PWEB_P6.Controllers
{
    public class UserRolesManagerController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserRolesManagerController(UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();

            foreach (var user in users)
            {
                userRolesViewModel.Add(new UserRolesViewModel {
                    UserId = user.Id,
                    PrimeiroNome = user.PrimeiroNome,
                    UltimoNome = user.UltimoNome,
                    UserName = user.UserName,
                    Roles = await _userManager.GetRolesAsync(user),
                    Avatar = user.Avatar
                });
            }

            return View(userRolesViewModel);
        }

        private async Task<List<string>> GetUserRoles(ApplicationUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }

        public async Task<IActionResult> Details(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            var manageUserRolesViewModels = new List<ManageUserRolesViewModel>();

            foreach (var role in await _roleManager.Roles.ToListAsync())
            {
                manageUserRolesViewModels.Add(new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name,
                    Selected = await _userManager.IsInRoleAsync(user, role.Name)
                });
            }

            ViewBag.UserName = user.UserName;
            ViewBag.Avatar = user.Avatar;
            return View(manageUserRolesViewModels);
        }
        [HttpPost]
        public async Task<IActionResult> Details(List<ManageUserRolesViewModel> model,
            string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return View();
            }

            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }

            result = await _userManager.AddToRolesAsync(
                user, 
                model
                    .Where(r => r.Selected)
                    .Select(r => r.RoleName)
                );

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }

            return RedirectToAction("Index");
        }
    }
}

PWEB-P6/Views/UserRolesManager/Details.cshtml
@model List<PWEB_P6.ViewModels.ManageUserRolesViewModel>
@{
    ViewData["Title"] = "Manage";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Manage User Roles</h2>
            @if (ViewBag.Avatar?.Length > 0)
            {
                <img id="MyAvatar" style="max-width: 100px; max-height: 100px"
                 src="data:image/*;base64,@(Convert.ToBase64String(ViewBag.Avatar))" />
            }
            <span class="badge bg-dark text-white">@ViewBag.UserName</span> Add / Remove Roles
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].RoleId" />
                    <input type="hidden" asp-for="@Model[i].RoleName" />
                    <input asp-for="@Model[i].Selected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].Selected">
                        @Model[i].RoleName
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary"
                   style="width:auto" />
            <a asp-action="Index" 
               class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

PWEB-P6/Views/UserRolesManager/Index.cshtml
@using PWEB_P6.Models
@model IEnumerable<PWEB_P6.ViewModels.UserRolesViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<h1>User Roles</h1>
<table class="table table-striped">
    <thead>
    <tr>
        <th></th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Roles</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var userRoles in Model)
    {
        <tr>
            <td>
                @if (userRoles.Avatar?.Length > 0)
                {
                    <img id="MyAvatar" style="max-width: 100px; max-height: 100px"
                     src="data:image/*;base64,@(Convert.ToBase64String(userRoles.Avatar))" />
                }
            </td>
            <td>@userRoles.PrimeiroNome</td>
            <td>@userRoles.UltimoNome</td>
            <td>@userRoles.UserName</td>
            <td>@string.Join(", ", userRoles.Roles.ToList())</td>
            <td>
                <a class="btn btn-primary"
                   asp-controller="UserRolesManager"
                   asp-action="Details"
                   asp-route-userId="@userRoles.UserId">Manage Roles</a>
            </td>
        </tr>
    }
    </tbody>
</table>