PWEB-P6/Models/Agendamento.cs
namespace PWEB_P6.Models
{
    public class Agendamento
    {
        public int Id { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime DataFim { get; set; }
        public int DuracaoEmHoras { get; set; }
        public int DuracaoEmMinutos { get; set; }
        public decimal Preco { get; set; }
        public DateTime DataHoraDoPedido { get; set; }

        public int TipoDeAulaId { get; set; }
        public TipoDeAula tipoDeAula { get; set; }

        // Relation ApplicationUser
        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
    }
}

PWEB-P6/ViewModels/AgendamentoViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace PWEB_P6.ViewModels
{
    public class AgendamentoViewModel
    {
        [Display(Name = "Data de Início", Prompt = "yyyy-mm-dd")]
        public DateTime DataInicio { get; set; }

        [Display(Name = "Data de Fim", Prompt = "yyyy-mm-dd")]
        public DateTime DataFim { get; set; }

        [Display(Name = "Tipo de aula", Prompt = "Escolha o tipo de aula que pretende")]
        public int TipoDeAulaId { get; set; }
    }
}

PWEB-P6/Controllers/AgendamentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEB_P6.Data;
using PWEB_P6.Models;
using PWEB_P6.ViewModels;

namespace PWEB_P6.Controllers
{
    public class AgendamentosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public AgendamentosController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Agendamentos
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Agendamentos
                .Include(a => a.tipoDeAula)
                .Include(a => a.ApplicationUser);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Agendamentos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Agendamentos == null)
            {
                return NotFound();
            }

            var agendamento = await _context.Agendamentos
                .Include(a => a.tipoDeAula)
                .Include(a => a.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (agendamento == null)
            {
                return NotFound();
            }

            return View(agendamento);
        }

        // GET: Agendamentos/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["TipoDeAulaId"] = new SelectList(_context.TipoDeAulas, "Id", "Id");
            return View();
        }

        // POST: Agendamentos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,DataInicio,DataFim,DuracaoEmHoras,DuracaoEmMinutos,Preco,DataHoraDoPedido,TipoDeAulaId")] Agendamento agendamento)
        {
            ModelState.Remove(nameof(agendamento.tipoDeAula));
            ModelState.Remove(nameof(agendamento.ApplicationUser));
            ModelState.Remove(nameof(agendamento.ApplicationUserId));

            agendamento.ApplicationUserId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                _context.Add(agendamento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoDeAulaId"] = new SelectList(_context.TipoDeAulas, "Id", "Id", agendamento.TipoDeAulaId);
            return View(agendamento);
        }

        // GET: Agendamentos/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Agendamentos == null)
            {
                return NotFound();
            }

            var agendamento = await _context.Agendamentos.FindAsync(id);
            if (agendamento == null)
            {
                return NotFound();
            }
            ViewData["TipoDeAulaId"] = new SelectList(_context.TipoDeAulas, "Id", "Id", agendamento.TipoDeAulaId);
            return View(agendamento);
        }

        // POST: Agendamentos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DataInicio,DataFim,DuracaoEmHoras,DuracaoEmMinutos,Preco,DataHoraDoPedido,TipoDeAulaId")] Agendamento agendamento)
        {
            if (id != agendamento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(agendamento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AgendamentoExists(agendamento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoDeAulaId"] = new SelectList(_context.TipoDeAulas, "Id", "Id", agendamento.TipoDeAulaId);
            return View(agendamento);
        }

        // GET: Agendamentos/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Agendamentos == null)
            {
                return NotFound();
            }

            var agendamento = await _context.Agendamentos
                .Include(a => a.tipoDeAula)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (agendamento == null)
            {
                return NotFound();
            }

            return View(agendamento);
        }

        // POST: Agendamentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Agendamentos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Agendamentos'  is null.");
            }
            var agendamento = await _context.Agendamentos.FindAsync(id);
            if (agendamento != null)
            {
                _context.Agendamentos.Remove(agendamento);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Agendamentos/Pedido
        public IActionResult Pedido()
        {
            ViewData["TipoDeAulaId"] = new SelectList(_context.TipoDeAulas.ToList(), "Id", "Nome");

            return View();
        }

        // POST: Agendamentos/Calcular
        [HttpPost]
        public async Task<IActionResult> Calcular([Bind("DataInicio,DataFim,TipoDeAulaId")] AgendamentoViewModel pedido)
        {
            if (pedido.DataInicio > pedido.DataFim)
            {
                ModelState.AddModelError("DataInicio", "A data de inicio deve ser sempre anterior à data de fim");
            }

            var tipoDeAula = _context.TipoDeAulas.Find(pedido.TipoDeAulaId);
            if (tipoDeAula == null)
            {
                ModelState.AddModelError("TipoDeAulaId", "Tipo de aula não existe");
            }

            if (!ModelState.IsValid)
            {
                ViewData["TipoDeAulaId"] = new SelectList(_context.TipoDeAulas.ToList(), "Id", "Nome");

                return View("Pedido");
            }
            
            var agendamento = new Agendamento();

            agendamento.DataInicio = pedido.DataInicio;
            agendamento.DataFim = pedido.DataFim;
            agendamento.TipoDeAulaId = pedido.TipoDeAulaId;
            agendamento.tipoDeAula = tipoDeAula;
            agendamento.ApplicationUserId = _userManager.GetUserId(User);

            agendamento.DuracaoEmHoras = (int) Math.Floor((agendamento.DataFim - agendamento.DataInicio).TotalHours);
            agendamento.DuracaoEmMinutos = (int)Math.Floor((agendamento.DataFim - agendamento.DataInicio).TotalMinutes);
            agendamento.Preco = tipoDeAula.ValorHora * agendamento.DuracaoEmHoras;
            agendamento.DataHoraDoPedido = DateTime.Now;

            return View("PedidoConfirmacao", agendamento);
        }

        // GET: Agendamentos/OsMeusAgendamentos
        public IActionResult OsMeusAgendamentos()
        {
            var listaAgendamentos = _context.Agendamentos
                .Include(a => a.tipoDeAula)
                .Include(a => a.ApplicationUser)
                .Where(a => a.ApplicationUserId == _userManager.GetUserId(User));

            return View(listaAgendamentos);
        }

        private bool AgendamentoExists(int id)
        {
          return _context.Agendamentos.Any(e => e.Id == id);
        }
    }
}

PWEB-P6/Views/Agendamentos/Create.cshtml
@model PWEB_P6.Models.Agendamento

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Agendamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFim" class="control-label"></label>
                <input asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DuracaoEmHoras" class="control-label"></label>
                <input asp-for="DuracaoEmHoras" class="form-control" />
                <span asp-validation-for="DuracaoEmHoras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DuracaoEmMinutos" class="control-label"></label>
                <input asp-for="DuracaoEmMinutos" class="form-control" />
                <span asp-validation-for="DuracaoEmMinutos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataHoraDoPedido" class="control-label"></label>
                <input asp-for="DataHoraDoPedido" class="form-control" />
                <span asp-validation-for="DataHoraDoPedido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoDeAulaId" class="control-label"></label>
                <select asp-for="TipoDeAulaId" class ="form-control" asp-items="ViewBag.TipoDeAulaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PWEB-P6/Views/Agendamentos/Delete.cshtml
@model PWEB_P6.Models.Agendamento

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agendamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DuracaoEmHoras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DuracaoEmHoras)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DuracaoEmMinutos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DuracaoEmMinutos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataHoraDoPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataHoraDoPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipoDeAula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipoDeAula.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PWEB-P6/Views/Agendamentos/Details.cshtml
@model PWEB_P6.Models.Agendamento

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Agendamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.PrimeiroNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.PrimeiroNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.UltimoNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.UltimoNome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataInicio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DuracaoEmHoras)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DuracaoEmHoras)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DuracaoEmMinutos)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DuracaoEmMinutos)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataHoraDoPedido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataHoraDoPedido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tipoDeAula)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tipoDeAula.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PWEB-P6/Views/Agendamentos/Edit.cshtml
@model PWEB_P6.Models.Agendamento

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Agendamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFim" class="control-label"></label>
                <input asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DuracaoEmHoras" class="control-label"></label>
                <input asp-for="DuracaoEmHoras" class="form-control" />
                <span asp-validation-for="DuracaoEmHoras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DuracaoEmMinutos" class="control-label"></label>
                <input asp-for="DuracaoEmMinutos" class="form-control" />
                <span asp-validation-for="DuracaoEmMinutos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataHoraDoPedido" class="control-label"></label>
                <input asp-for="DataHoraDoPedido" class="form-control" />
                <span asp-validation-for="DataHoraDoPedido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoDeAulaId" class="control-label"></label>
                <select asp-for="TipoDeAulaId" class="form-control" asp-items="ViewBag.TipoDeAulaId"></select>
                <span asp-validation-for="TipoDeAulaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PWEB-P6/Views/Agendamentos/Index.cshtml
@model IEnumerable<PWEB_P6.Models.Agendamento>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationUser.PrimeiroNome)
        </th>
        <th>
                @Html.DisplayNameFor(model => model.ApplicationUser.UltimoNome)
        </th>
        <th>
                @Html.DisplayNameFor(model => model.ApplicationUser.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataFim)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DuracaoEmHoras)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DuracaoEmMinutos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataHoraDoPedido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipoDeAula)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.PrimeiroNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.UltimoNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataInicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataFim)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DuracaoEmHoras)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DuracaoEmMinutos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataHoraDoPedido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tipoDeAula.Id)
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
    </tr>
}
    </tbody>
</table>

PWEB-P6/Views/Agendamentos/OsMeusAgendamentos.cshtml
@model IEnumerable<PWEB_P6.Models.Agendamento>

@{
    ViewData["Title"] = "Os meus agendamentos";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<h1>Os meus agendamentos</h1>
<p>
    <a asp-action="Pedido">Novo Agendamento</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>UserName</th>
        <th>Tipo de Aula</th>                        
        <th>
            Início
        </th>
        <th>
            Fim
        </th>
        <th>
            Preço
        </th>
         
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ApplicationUser.UserName</td>
            <td>
                @Html.DisplayFor(modelItem => item.tipoDeAula.Nome)
            </td>                                
            <td>
                @Html.DisplayFor(modelItem => item.DataInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataFim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>               
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

PWEB-P6/Views/Agendamentos/Pedido.cshtml
@model PWEB_P6.ViewModels.AgendamentoViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h4>Agendamento - Pedido</h4>
<hr />

@if (User.Identity.IsAuthenticated)
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Calcular">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="TipoDeAulaId" class="control-label"></label>
                    <select asp-for="TipoDeAulaId" class="form-control" asp-items="ViewBag.TipoDeAulaId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="DataInicio" class="control-label"></label>
                    <input asp-for="DataInicio" class="form-control"/>
                    <span asp-validation-for="DataInicio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DataFim" class="control-label"></label>
                    <input asp-for="DataFim" class="form-control"/>
                    <span asp-validation-for="DataFim" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Calcular" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
}
else
{
    <p class="alert alert-warning">Só utilizadores autenticados é que podem efetuar agendamentos. Por favor, autentique-se.</p>
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

PWEB-P6/Views/Agendamentos/PedidoConfirmacao.cshtml
@model PWEB_P6.Models.Agendamento

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<h4>Agendamento - Confirmação</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" asp-for="DuracaoEmHoras" />
            <input type="hidden" asp-for="DuracaoEmMinutos" />
            <input type="hidden" asp-for="Preco" />
            <input type="hidden" asp-for="TipoDeAulaId" />
            <input type="hidden" asp-for="DataInicio" />
            <input type="hidden" asp-for="DataFim" />
            <input type="hidden" asp-for="DataHoraDoPedido" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tipo de Aula</label>
                <input type="text" class="form-control form-control-lg" readonly disabled value="@Model.tipoDeAula.Nome" />
            </div>
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" readonly disabled />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFim" class="control-label"></label>
                <input asp-for="DataFim" class="form-control" readonly disabled />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>                        
           
            <div class="form-group pt-4">
                <p class="alert alert-info">Este pedido de agendamento tem um custo de  <b>@Model.Preco</b> Euros.
                    
                    </p>
            </div>
            <div class="form-group">
                <p>Por favor escolha uma das seguintes opções:</p>
                <input type="submit" value="Confirmar Agendamento" class="btn btn-primary" />
                <a class="btn btn-warning" asp-controller="Agendamentos" asp-action="Pedido">Cancelar pedido</a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>