PWEB-P6/Controllers/RoleManagerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PWEB_P6.Data;

namespace PWEB_P6.Controllers
{
    public class RoleManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleManagerController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            return RedirectToAction("Index");
        }
    }
}

PWEB-P6/Views/RoleManager/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Role Manager";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<h1>Gestão de Roles</h1>
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="AddRole" asp-controller="RoleManager">
            <div class="input-group">
                <input name="roleName" class="form-control">
                <span class="input-group-btn">
                    <button class="btn btn-warning">Add New Role</button>
                </span>
            </div>
        </form>
    </div>
</div>
<table class="table table-striped table-hover table-bordered mt-4">
    <thead>
    <tr>
        <th>Role</th>
        <th>Id</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Id
            </td>
        </tr>
    }
    </tbody>
</table>